---
title: "Data Camp Statistics"
output: 
 html_document:
  self_contained: true
  theme: flatly
  highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=T, echo=F, cache=F, message=F, warning=F)
options(RCHART_WIDTH = 800, RCHART_HEIGHT = 400)
```

```{r}

library(dplyr)
library(lubridate)
library(stringr)
library(rCharts)
library(ggplot2)

rchart_date_format <- str_c("#!",
      "function(d){",
        "f =  d3.time.format.utc('%Y-%m-%d');",
        "return f(new Date( d*24*60*60*1000 ));",
      "}",
    "!#")

if (student == 'william') {
  work_days = c(2,3,4,5,6)
} else if (student == 'russell') {
  work_days = c(2,3,4,5)    
}

```

> Datcamp stats for **`r student`**

***
# Tracking
***

## Cummulative daily exercises by month

```{r chart_month_cum, results = 'asis'}

df_stats2 <- df_stats %>%
    mutate(
      date = as.Date(Date, "%m/%d/%Y"),
      year = year(date),
      month = str_pad(month(date), 2, pad = "0"),
      mday = mday(date),
      exercises_cumsum = cumsum(Exercises)
    ) %>%
    group_by(month) %>%
    mutate(
      exercises_cumsum_month = cumsum(Exercises)
    )

n <- nPlot(exercises_cumsum_month ~ mday, data = df_stats2, group = "month", type = 'lineChart')
n$print(include_assets=T)

```

## Same chart but with ggplot2

```{r, fig.width = 9}

ggplot(df_stats2, aes(mday, exercises_cumsum_month, color = as.factor(month))) + 
  geom_line(size = 1.5) +
  theme_minimal() + 
  theme(legend.position = "top") + 
  guides(color=guide_legend(title="Month"))


```

## Weekly exercises completed

```{r, results = 'asis'}

df_stats_week <- df_stats %>%
  mutate(
    date = as.Date(Date, "%m/%d/%Y"),
    iso_week = isoweek(date)
    ) %>%
  group_by(iso_week) %>%
  summarize(
    start_day = min(date),
    total_exercises = sum(Exercises, na.rm=T)
  )

n <- nPlot(total_exercises ~ start_day, data = df_stats_week, type = 'multiBarChart')
n$xAxis(tickFormat = rchart_date_format)
n$print(include_assets=T)


```

## Daily exercises completed

```{r, fig.width = 9}

df_stats %>%
  mutate(
    date = as.Date(Date, "%m/%d/%Y")
    ) %>%
  ggplot(aes(x = date, y = Exercises)) +
  geom_bar(
    stat = 'identity',
    alpha = .8,
    fill = 'blue',
    color = 'white',
    linewidth = .2,
    width = 1)
  

```

***
# Overview
***

## Daily exercises completed ordered by most completed (on work days)

```{r cdf, results = 'asis'}

df_plot <- df_stats %>%
  mutate(
    date = as.Date(Date, "%m/%d/%Y"),
    wday = wday(date)
    ) %>%
  filter(
    Exercises > 0,
    wday %in% work_days
    ) %>%
  arrange(desc(Exercises)) %>%
  mutate(
    rank = row_number(-Exercises)
    )

n <- nPlot(Exercises ~ rank, data = df_plot, type = 'multiBarChart')
n$print(include_assets=T)



```

## Histogram of daily exercises (on work days)

```{r, fig.width = 9}

df_plot <- df_stats %>%
  mutate(
    date = as.Date(Date, "%m/%d/%Y"),
    wday = wday(date)
    ) %>%
  filter(
    Exercises > 0,
    wday %in% work_days
    )
  
ggplot(df_plot, aes(Exercises)) +
  geom_histogram(
    boundary = 0,
    alpha = .6,
    fill = 'blue',
    binwidth = 5,
    color = 'white')
  

```
